---
# Set nginx base configuration file
- name: configure nginx
  become: true
  template:
    src: nginx_config.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
