---
- hosts: node

  vars_files:
    - vars/main.yml

  roles:
    - ansible-role-firewalld
    - ansible-role-nginx

  tasks:
    - name: Copy Nginx server configuration in place.
      become: yes
      template:
        src: templates/plex.conf.j2
        dest: /etc/nginx/conf.d/plex.conf
        mode: 0644
      notify: restart nginx

    - name: Create dir for persistent vol
      file:
        path: "{{ plex_vol }}"
        state: directory
        mode: 0775
        owner: ansible
        group: deploy
      become: yes

    - name: Pull Plex Container
      community.docker.docker_image:
        name: "docker.io/plexinc/pms-docker"
        tag: latest
        pull: yes
        state: present

    - name: Restart Plex Container
      community.docker.docker_container:
        name: plex
        image: plexinc/pms-docker
        state: started
        recreate: yes
        hostname: "{{ subdomain }}.{{ domain }}"
        restart_policy: "no"
        network_mode: "bridge"
        ports: 
          - "{{ listen_port }}:{{ container_port }}"
          - "3005:3005/tcp"
          - "8324:8324/tcp"
          - "32469:32469/tcp"
          - "1900:1900/udp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
        env:
            PUID: '1001'
            PGID: '1001'
            TZ: 'America/New_York'
            PLEX_CLAIM: 'claim-rJH-s1YEBaftPZgNE3Sx'
            ADVERTISE_IP: "https://plex.engelcc.com:32400"
        volume:
          - /mnt/music:/data/music:ro
          - /mnt/plex/4k_Movies:/data/4k_Movies
          - /mnt/plex/Movies:/data/Movies
          - /mnt/plex/Anime:/data/Anime
          - /mnt/plex/TV:/data/TV
          - "{{ plex_vol }}:/config"
        detach: yes
      tags: container-restart
