---
- hosts: localhost
#  become: true

  vars_files:
    - vars/main.yml

  roles:
    - ansible-role-firewalld
    - ansible-role-nginx

  tasks:
    - name: Copy Nginx server configuration in place.
      become: yes
      template:
        src: templates/nextcloud.conf.j2
        dest: /etc/nginx/conf.d/nextcloud.conf
        mode: 0644
      notify: restart nginx

    - name: Create dir for persistent nextcloud vol
      file:
        path: "{{ nextcloud_vol }}"
        state: directory
        mode: 777
        owner: ansible
        group: ansible
      become: yes

    - name: Pull Nextcloud Container
      containers.podman.podman_image:
        name: "docker.io/library/nextcloud"
        tag: stable
        pull: yes
        state: present

    - name: Restart Nextcloud Container
      community.docker.docker_container:
        name: nextcloud
        image: library/nextcloud
        state: started
        recreate: yes
        hostname: "{{ subdomain }}.{{ domain }}"
        restart_policy: "unless-stopped"
        network_mode: "bridge"
        ports: 
          - "8080:80"
        env:
            JELLYFIN_PublishedServerUrl: "http://jellyfin.engelcc.com"
        volumes:
          - "{{ nextcloud_vol }}:/var/www/html"
        detach: yes
        tags: container-restart
