---
# Set sshd configuration file
- name: configure sshd
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify: restart sshd

