---
# tasks file for firewalld
# install ssh packages
- name: Check if firewalld package is installed (on RHEL).
  become: yes
  command: yum list installed firewalld
  args:
    warn: false
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
#    - firewall_disable_firewalld
  check_mode: false

- name: Enable firewalld service
  become: yes
  service:
    name: firewalld
    enabled: "{{ firewalld_enabled }}"

- name: Allow firewalld services
  become: yes
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewalld_allowed_services }}"
  notify:
    - restart firewalld

- name: Allow firewalld ports
  become: yes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewalld_allowed_tcp_ports }}"
  when: firewalld_allowed_tcp_ports is defined
  notify:
    - restart firewalld
