---
- hosts: node

  vars_files:
    - vars/main.yml

  roles:
    - ansible-role-firewalld
    - ansible-role-nginx

  tasks:
    - name: Copy Nginx server configuration in place.
      become: yes
      template:
        src: templates/navidrome.conf.j2
        dest: /etc/nginx/conf.d/navidrome.conf
        mode: 0644
      notify: restart nginx

    - name: Create dir for persistent vol
      file:
        path: "{{ podman_vol }}"
        state: directory
        mode: 0777
        owner: ansible
        group: deploy
      become: yes

    - name: Pull Navidrome Container
      containers.podman.podman_image:
        name: "docker.io/deluan/navidrome"
        tag: latest
        pull: yes
        state: present

    - name: Restart Navidrome Container
      containers.podman.podman_container:
        name: navidrome
        image: deluan/navidrome
        state: started
        #restart: yes
        recreate: yes
        hostname: "{{ subdomain }}.{{ domain }}"
        restart_policy: "no"
        privileged: no #yes 
        network: slirp4netns
        publish: "{{ listen_port }}:{{ container_port }}"
        env:
            PUID: '1000'
            PGID: '1000'
        volume:
          - /mnt/music:/music:ro
          - /mnt/navidrome:/data
        detach: yes
      tags: container-restart
