---
- hosts: localhost
  tasks:
    - name: add rpmfusion repos
      become: yes
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-33.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-33.noarch.rpm

    #-- Needs to be tested
    #-- Mullvad VPN
    #- name: download mullvad rpm
    #  become: yes
    #  command: wget --content-disposition https://mullvad.net/download/rpm/latest -o mullvad.rpm
    #  warn: false
    # 
    #- name: install mullvad rpm
    #  become: yes
    #  command: dnf install -y mullvad.rpm
    #  warn: false

    #-- Install workstation packages
    - name: install ws packages
      become: yes
      dnf:
        name: "{{ packages }}"
        state: present
      with_items:
        - awscli
        - chromium-browser-privacy
        - curl
        - dconf-editor
        - ffmpeg-libs
        - gnome-tweaks
        - git
        - hexchat
        - htop
        # - intel-undervolt # not working w/ firmware update
        - iotop
        - jq
        - lm_sensors
        - ncdu
        - neofetch
        - pavucontrol
        - powertop
        - remmina
        - stow
        - terminator
        - tlp
        - tmux
        - tree
        - vim
        - wireguard-tools
        - wget

    - name: Add the flathub flatpak repository remote to the user installation
      become: yes
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      tags: flatpak-install

    - name: Add the flathub repo for joey
      become: yes
      become_user: joey
      flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      tags: flatpak-install

    #-- Install System Flatpaks
    - name: Install system flatpak
      become: yes
      flatpak:
        name: "{{ item }}"
        state: present
      with_items:
        - "com.getpostman.Postman"
        - "com.slack.Slack"
        - "io.dbeaver.DBeaverCommunity"
      tags: flatpak-install

    #-- Install User flatpaks
    - name: install telegram flatpak
      become: yes
      become_user: joey
      flatpak:
        name: "{{ item }}"
        state: present
        method: user
      with_items:
        - "com.discordapp.Discord"
        - "com.bitwarden.desktop"
        - "com.spotify.Client"
        - "im.riot.Riot"
        - "io.mgba.mGBA"
        - "org.telegram.desktop"
      tags: flatpak-install

